### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [ambidextrousTx/RGrep-CPP#1]
Dear Ravi,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by ambidextrousTx** [comment]
Hi @sergeevabc - thanks for showing an interest in this project. I'll work on adding some new features and creating binaries for people of different platforms to use. Thanks :-)

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?

**Comment by sergeevabc** [comment]
Six months passed. Err… Hello?

**Comment by sergeevabc** [comment]
@ambidextrousTx, did you get a chance to look into this more thoroughly?
